DELETE FROM dbo.CMeterage WHERE MeterageDate='20150913' AND StaffId=375

DELETE FROM dbo.CMeterage WHERE EGIGuid IN 
(SELECT Guid FROM 
EQ.Counter.Index AS GI 
WHERE Date=CONVERT(SMALLDATETIME,DATEADD(DAY, DATEDIFF(day, 0, GETDATE()), -1)) AND GISId=112)
